# Default pipeline to build, check and test SAWP
trigger:
  - main
  - staging
pr:
  - main
  - staging

# Run daily at midnight UTC if there has been a code change since the last scheduled run
schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

resources:
- repo: self

variables:
- name: rust_msrv
  value: 1.63.0

stages:
- stage: test
  pool: $(pool)
  dependsOn: []
  jobs:
  - job: test
    displayName: Test SAWP
    steps:
      - template: qa-steps.yml
        parameters:
          rust_msrv: ${{ variables.rust_msrv }}
      - template: package-steps.yml

      # Check if cargo release would pass
      - script: cargo release --allow-branch HEAD --workspace -- patch
        displayName: check release
- stage: fuzz
  pool: $(pool)
  dependsOn: []
  jobs:
  - job: fuzz
    displayName: Fuzz SAWP
    steps:
      - template: fuzz-steps.yml
