[package]
name = "sawp-diameter"
version = "0.12.1"
authors = ["Canadian Centre for Cyber Security <sa-sawp@cyber.gc.ca>"]
description = "SAWP Protocol Parser for Diameter"
readme = "../README.md"
edition = "2021"
license = "MIT"
repository = "https://github.com/CybercentreCanada/sawp"
homepage = "https://github.com/CybercentreCanada/sawp"
keywords = ["diameter", "parser", "protocol", "mobility", "core-network"]
categories = ["parsing", "network-programming"]
include = [
    "Cargo.toml",
    "../LICENSE",
    "../README.md",
    "src/**/*.rs",
]

[features]
verbose = ["sawp/verbose"]

[dependencies]
sawp = { path = "..", version = "^0.12.1" }
sawp-flags = { path = "../sawp-flags", version = "^0.12.1" }
nom = "7.1.1"
num_enum = "0.5.1"

[dev-dependencies]
rstest = "0.6.4"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

# Override default replacements
[package.metadata.release]
pre-release-replacements = []
